# Generated by Django 5.2.3 on 2025-08-18 17:26

from django.db import migrations

def fill_subjects(apps, schema_editor):
    StudyMaterial = apps.get_model('accounts', 'StudyMaterial')
    Subject = apps.get_model('accounts', 'Subject')
    
    # Создаем временный предмет для материалов без предмета
    temp_subject, created = Subject.objects.get_or_create(
        name='Общие материалы',
        defaults={'description': 'Временная категория для материалов без предмета'}
    )
    
    # Назначаем этот предмет всем существующим материалам
    StudyMaterial.objects.update(subject=temp_subject)
    
class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_studymaterial_subject_alter_studymaterial_author_and_more'),
    ]

    operations = [
        migrations.RunPython(fill_subjects),
    ]
