# Generated by Django 5.2.3 on 2025-08-18 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_fill_study_materials_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studymaterial',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='accounts.subject', verbose_name='Предмет'),
        ),
    ]
